### ISSUE TITLE
Bug in get_currency_equivalence

### ISSUE THREAD

**Issue by PierreGtch** [SEM1INFOENS/multiplanner#109]
I don't know if it will happen again, I only got this once and diden't manage to reproduce it...
```
Internal Server Error: /
Traceback (most recent call last):
  File "/home/pierre/.conda/envs/anaconda_root/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/pierre/.conda/envs/anaconda_root/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/pierre/.conda/envs/anaconda_root/lib/python3.7/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/pierre/.conda/envs/anaconda_root/lib/python3.7/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/pierre/Documents/projets/multiplanner/presentation/views.py", line 22, in index
    spent, due = balance_of_user(user)
  File "/home/pierre/Documents/projets/multiplanner/presentation/functions.py", line 88, in balance_of_user
    amount = get_currency_equivalence(b.amount.currency,user_profile.default_currency,amount)
  File "/home/pierre/Documents/projets/multiplanner/accounting/webScraping.py", line 20, in get_currency_equivalence
    return float(tag[0].get_text()[0:8])
ValueError: could not convert string to float: '502,430.'
```

**Comment by PierreGtch** [comment]
J'ai eu le bug une nouvelle fois

**Comment by PierreGtch** [comment]
@Kessaye Apparently djmoney can take care of the exchange rates : 
```python
from djmoney.contrib.exchange.models import convert_money
convert_money(Money(100, 'EUR'), 'USD')
```
see : https://github.com/django-money/django-money#working-with-exchange-rates

**Comment by Kessaye** [comment]
How did you get this bug : for what currencies and amounts?

**Comment by Kessaye** [comment]
@PierreGtch  Django money is not really up to date so it is a bad idea + plus it's a bit too late for me to change into the django money

**Comment by PierreGtch** [comment]
I just had this bug two times when creating transactions in a currency different than my user's default currency

**Comment by Kessaye** [comment]
ok i will handle it 
I know what's the problem ... Easy to solve :)

**Comment by Kessaye** [comment]
I'll do it tomorrow
