### ISSUE TITLE
what is selenium ???

### ISSUE THREAD

**Issue by PierreGtch** [SEM1INFOENS/multiplanner#130]
```
ERROR: test_integration (multiplanner.tests.AccountTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pierre/.conda/envs/anaconda_root/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/home/pierre/.conda/envs/anaconda_root/lib/python3.7/subprocess.py", line 756, in __init__
    restore_signals, start_new_session)
  File "/home/pierre/.conda/envs/anaconda_root/lib/python3.7/subprocess.py", line 1499, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'geckodriver': 'geckodriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pierre/Documents/projets/multiplanner/multiplanner/tests.py", line 20, in setUp
    self.selenium = webdriver.Firefox()
  File "/home/pierre/.conda/envs/anaconda_root/lib/python3.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 164, in __init__
    self.service.start()
  File "/home/pierre/.conda/envs/anaconda_root/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH. 


----------------------------------------------------------------------

```

**Comment by Z-ephyr** [comment]
selenium is the thing used by roman for test

**Comment by Z-ephyr** [comment]
https://github.com/SEM1INFOENS/multiplanner/commit/ac18603b4af0d0f11e728c14d3531fb045c8c53e#diff-a9d30f781fc215c34afa001b83f69f23

>> it maybe that problem

**Comment by Z-ephyr** [comment]
The line should not be deleted
