### ISSUE TITLE
Main page is broken, problem with db

### ISSUE THREAD

**Issue by kameronton** [SEM1INFOENS/multiplanner#36]
Here is what I got when deleted the old db, created a new one and a new user:

```

Request Method: | GET
-- | --
http://localhost:8000/
2.1.2
OperationalError
no such table: agenda_event


```

```
Environment:


Request Method: GET
Request URL: http://localhost:8000/

Django Version: 2.1.2
Python Version: 3.6.4
Installed Applications:
['accounting.apps.AccountingConfig',
 'agenda.apps.AgendaConfig',
 'groups.apps.GroupsConfig',
 'notifications.apps.NotificationsConfig',
 'presentation.apps.PresentationConfig',
 'relationships.apps.RelationshipsConfig',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.admindocs',
 'friendship']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']


Template error:
In template /Users/kameron/master/software_engineering/multiplanner/multiplanner/common_static/base_template.html, error at line 69
   no such table: agenda_event
   59 :     {% endif %}
   60 : 
   61 :   </head>
   62 :   <body>
   63 : 
   64 :     <div class="container" id="content">
   65 :       {% block content %}{% endblock %}
   66 :     </div>
   67 :     <!-- Optional JavaScript -->
   68 :     <!-- jQuery first, then Popper.js, then Bootstrap JS -->
   69 :     <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sh a384-q8i/X+965DzO0rT7abK41J StQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
   70 :     <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
   71 :     <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
   72 :   </body>
   73 : </html>
   74 : 

Traceback:

File "/Users/kameron/master/software_engineering/env/lib/python3.6/site-packages/django/db/backends/utils.py" in _execute
  85.                 return self.cursor.execute(sql, params)

File "/Users/kameron/master/software_engineering/env/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py" in execute
  296.         return Database.Cursor.execute(self, query, params)

The above exception (no such table: agenda_event) was the direct cause of the following exception:

File "/Users/kameron/master/software_engineering/env/lib/python3.6/site-packages/django/core/handlers/exception.py" in inner
  34.             response = get_response(request)

File "/Users/kameron/master/software_engineering/env/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response
  126.                 response = self.process_exception_by_middleware(e, request)

File "/Users/kameron/master/software_engineering/env/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response
  124.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/Users/kameron/master/software_engineering/env/lib/python3.6/site-packages/django/contrib/auth/decorators.py" in _wrapped_view
  21.                 return view_func(request, *args, **kwargs)

File "/Users/kameron/master/software_engineering/multiplanner/presentation/views.py" in index
  25.     return render(request, 'users/index.html', context)

File "/Users/kameron/master/software_engineering/env/lib/python3.6/site-packages/django/shortcuts.py" in render
  36.     content = loader.render_to_string(template_name, context, request, using=using)

File "/Users/kameron/master/software_engineering/env/lib/python3.6/site-packages/django/template/loader.py" in render_to_string
  62.     return template.render(context, request)

File "/Users/kameron/master/software_engineering/env/lib/python3.6/site-packages/django/template/backends/django.py" in render
  61.             return self.template.render(context)

File "/Users/kameron/master/software_engineering/env/lib/python3.6/site-packages/django/template/base.py" in render
  171.                     return self._render(context)

File "/Users/kameron/master/software_engineering/env/lib/python3.6/site-packages/django/template/base.py" in _render
  163.         return self.nodelist.render(context)

File "/Users/kameron/master/software_engineering/env/lib/python3.6/site-packages/django/template/base.py" in render
  937.                 bit = node.render_annotated(context)

File "/Users/kameron/master/software_engineering/env/lib/python3.6/site-packages/django/template/base.py" in render_annotated
  904.             return self.render(context)

File "/Users/kameron/master/software_engineering/env/lib/python3.6/site-packages/django/template/loader_tags.py" in render
  150.             return compiled_parent._render(context)

File "/Users/kameron/master/software_engineering/env/lib/python3.6/site-packages/django/template/base.py" in _render
  163.         return self.nodelist.render(context)

File "/Users/kameron/master/software_engineering/env/lib/python3.6/site-packages/django/template/base.py" in render
  937.                 bit = node.render_annotated(context)

File "/Users/kameron/master/software_engineering/env/lib/python3.6/site-packages/django/template/base.py" in render_annotated
  904.             return self.render(context)

File "/Users/kameron/master/software_engineering/env/lib/python3.6/site-packages/django/template/loader_tags.py" in render
  62.                 result = block.nodelist.render(context)

File "/Users/kameron/master/software_engineering/env/lib/python3.6/site-packages/django/template/base.py" in render
  937.                 bit = node.render_annotated(context)

File "/Users/kameron/master/software_engineering/env/lib/python3.6/site-packages/django/template/base.py" in render_annotated
  904.             return self.render(context)

File "/Users/kameron/master/software_engineering/env/lib/python3.6/site-packages/django/template/defaulttags.py" in render
  308.             if match:

File "/Users/kameron/master/software_engineering/env/lib/python3.6/site-packages/django/db/models/query.py" in __bool__
  272.         self._fetch_all()

File "/Users/kameron/master/software_engineering/env/lib/python3.6/site-packages/django/db/models/query.py" in _fetch_all
  1186.             self._result_cache = list(self._iterable_class(self))

File "/Users/kameron/master/software_engineering/env/lib/python3.6/site-packages/django/db/models/query.py" in __iter__
  54.         results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)

File "/Users/kameron/master/software_engineering/env/lib/python3.6/site-packages/django/db/models/sql/compiler.py" in execute_sql
  1065.             cursor.execute(sql, params)

File "/Users/kameron/master/software_engineering/env/lib/python3.6/site-packages/django/db/backends/utils.py" in execute
  100.             return super().execute(sql, params)

File "/Users/kameron/master/software_engineering/env/lib/python3.6/site-packages/django/db/backends/utils.py" in execute
  68.         return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)

File "/Users/kameron/master/software_engineering/env/lib/python3.6/site-packages/django/db/backends/utils.py" in _execute_with_wrappers
  77.         return executor(sql, params, many, context)

File "/Users/kameron/master/software_engineering/env/lib/python3.6/site-packages/django/db/backends/utils.py" in _execute
  85.                 return self.cursor.execute(sql, params)

File "/Users/kameron/master/software_engineering/env/lib/python3.6/site-packages/django/db/utils.py" in __exit__
  89.                 raise dj_exc_value.with_traceback(traceback) from exc_value

File "/Users/kameron/master/software_engineering/env/lib/python3.6/site-packages/django/db/backends/utils.py" in _execute
  85.                 return self.cursor.execute(sql, params)

File "/Users/kameron/master/software_engineering/env/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py" in execute
  296.         return Database.Cursor.execute(self, query, params)

Exception Type: OperationalError at /
Exception Value: no such table: agenda_event

```

Who can resolve this? I think it is highly related to that agenda page didn't work for me

**Comment by PierreGtch** [comment]
@kameronton did you run `python3 manage.py migrate --run-syncdb` ?

**Comment by PierreGtch** [comment]
@kameronton I just deleted my db and created a new one but I don't have the error...

**Comment by DuncanSussfeld** [comment]
@PierreGtch our error seems related to this one, because both mention a problem sith an "agenda_event" table

here's what I get:
`Performing system checks...

System check identified no issues (0 silenced).
November 28, 2018 - 10:43:26
Django version 2.1.2, using settings 'multiplanner.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\Duncan\Documents\Cours\M1_S1\Software_Engineering\Tests Python\venv\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Duncan\Documents\Cours\M1_S1\Software_Engineering\Tests Python\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 296, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such column: agenda_event.creation_date

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Duncan\Documents\Cours\M1_S1\Software_Engineering\Tests Python\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Duncan\Documents\Cours\M1_S1\Software_Engineering\Tests Python\venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Duncan\Documents\Cours\M1_S1\Software_Engineering\Tests Python\venv\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Duncan\Documents\Cours\M1_S1\Software_Engineering\Tests Python\venv\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\Duncan\Documents\Cours\M1_S1\Software_Engineering\multiplanner\presentation\views.py", line 25, in index
    return render(request, 'users/index.html', context)
  File "C:\Users\Duncan\Documents\Cours\M1_S1\Software_Engineering\Tests Python\venv\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\Duncan\Documents\Cours\M1_S1\Software_Engineering\Tests Python\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\Duncan\Documents\Cours\M1_S1\Software_Engineering\Tests Python\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\Duncan\Documents\Cours\M1_S1\Software_Engineering\Tests Python\venv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Users\Duncan\Documents\Cours\M1_S1\Software_Engineering\Tests Python\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\Duncan\Documents\Cours\M1_S1\Software_Engineering\Tests Python\venv\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Users\Duncan\Documents\Cours\M1_S1\Software_Engineering\Tests Python\venv\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Users\Duncan\Documents\Cours\M1_S1\Software_Engineering\Tests Python\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Users\Duncan\Documents\Cours\M1_S1\Software_Engineering\Tests Python\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\Duncan\Documents\Cours\M1_S1\Software_Engineering\Tests Python\venv\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Users\Duncan\Documents\Cours\M1_S1\Software_Engineering\Tests Python\venv\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Users\Duncan\Documents\Cours\M1_S1\Software_Engineering\Tests Python\venv\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Users\Duncan\Documents\Cours\M1_S1\Software_Engineering\Tests Python\venv\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Users\Duncan\Documents\Cours\M1_S1\Software_Engineering\Tests Python\venv\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Users\Duncan\Documents\Cours\M1_S1\Software_Engineering\Tests Python\venv\lib\site-packages\django\template\defaulttags.py", line 308, in render
    if match:
  File "C:\Users\Duncan\Documents\Cours\M1_S1\Software_Engineering\Tests Python\venv\lib\site-packages\django\db\models\query.py", line 272, in __bool__
    self._fetch_all()
  File "C:\Users\Duncan\Documents\Cours\M1_S1\Software_Engineering\Tests Python\venv\lib\site-packages\django\db\models\query.py", line 1186, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\Duncan\Documents\Cours\M1_S1\Software_Engineering\Tests Python\venv\lib\site-packages\django\db\models\query.py", line 54, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "C:\Users\Duncan\Documents\Cours\M1_S1\Software_Engineering\Tests Python\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1065, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Duncan\Documents\Cours\M1_S1\Software_Engineering\Tests Python\venv\lib\site-packages\django\db\backends\utils.py", line 100, in execute
    return super().execute(sql, params)
  File "C:\Users\Duncan\Documents\Cours\M1_S1\Software_Engineering\Tests Python\venv\lib\site-packages\django\db\backends\utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\Users\Duncan\Documents\Cours\M1_S1\Software_Engineering\Tests Python\venv\lib\site-packages\django\db\backends\utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\Duncan\Documents\Cours\M1_S1\Software_Engineering\Tests Python\venv\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Duncan\Documents\Cours\M1_S1\Software_Engineering\Tests Python\venv\lib\site-packages\django\db\utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Duncan\Documents\Cours\M1_S1\Software_Engineering\Tests Python\venv\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Duncan\Documents\Cours\M1_S1\Software_Engineering\Tests Python\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 296, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such column: agenda_event.creation_date
[28/Nov/2018 10:43:37] "GET / HTTP/1.1" 500 217000
Not Found: /favicon.ico
[28/Nov/2018 10:43:37] "GET /favicon.ico HTTP/1.1" 404 3157`

**Comment by PierreGtch** [comment]
@kameronton @DuncanSussfeld I still don't have that error..

**Comment by kameronton** [comment]
It suddenly disappeared for me...

**Comment by Z-ephyr** [comment]
I don't have this error either...

**Comment by Z-ephyr** [comment]
@DuncanSussfeld @MaloPerez Do you still have this issue?

**Comment by MaloPerez** [comment]
Yes....

**Comment by MaloPerez** [comment]
Not a lot, this makes it impossible to vizualize anything... @kameronton did you do anything to fix your problem ?

**Comment by kameronton** [comment]
Deleted DB and used --run-syncdb, both several times :)

**Comment by MaloPerez** [comment]
Thanks ! It’s working !
